modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
displayURL="https://github.com/shizotoaster/puncher-java"
logoFile = "puncher-banner.png"
authors = '''
shizotoaster
'''
description = '''
Ultimate boat/minecart destroyer!!!1!
'''

[[dependencies.${name}]]
modId = "minecraft"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"

[modproperties.${name}]
catalogueImageIcon="puncher-icon.png"